# Получить список всех сущностей
GET http://localhost:8080/api/v1/car/list
content-type: application/xml

###

# Получить пагинированный список всех сущностей
GET http://localhost:8080/api/v1/car/page?offset=0&size=10&releaseYear=2020&model=LS&engineType=PETROL
content-type: application/xml

# Filters:
# - model
# - releaseYear
# - engineType
# - transmissionType
# - driveType

# Query params:
# - offset
# - size

###

# Найти сущность по id
GET http://localhost:8080/api/v1/car/find?id=03ea570d-bd63-4ee1-bd63-df9032c32104
content-type: application/xml

###

# Сохранить объект
PUT http://localhost:8080/api/v1/car/save
content-type: application/xml

<car>
    <brand>audi</brand>
    <model>A4</model>
    <releaseYear>2021</releaseYear>
    <dateOfReceiptIntoStock>2021-01-15</dateOfReceiptIntoStock>
    <body>
        <type>SEDAN</type>
        <color>WHITE</color>
    </body>
    <engine>
        <type>DIESEL</type>
        <capacity>100</capacity>
        <power>220</power>
        <torque>25</torque>
    </engine>
    <transmission>
        <type>AUTOMATIC</type>
        <numberOfGears>5</numberOfGears>
    </transmission>
    <drive>REAR</drive>
    <salon>
        <color>WHITE</color>
        <type>NYLON</type>
    </salon>
    <state>AVAILABLE</state>
</car>

###

# Обновить объект
PUT http://localhost:8080/api/v1/car/save
content-type: application/xml

<car>
    <id>03ea570d-bd63-4ee1-bd63-df9032c32104</id>
    <brand>audi</brand>
    <model>A4</model>
    <releaseYear>2021</releaseYear>
    <dateOfReceiptIntoStock>2021-01-16</dateOfReceiptIntoStock>
    <body>
        <type>SEDAN</type>
        <color>WHITE</color>
    </body>
    <engine>
        <type>DIESEL</type>
        <capacity>100</capacity>
        <power>220</power>
        <torque>25</torque>
    </engine>
    <transmission>
        <type>AUTOMATIC</type>
        <numberOfGears>5</numberOfGears>
    </transmission>
    <drive>REAR</drive>
    <salon>
        <color>WHITE</color>
        <type>NYLON</type>
    </salon>
    <state>RESERVED</state>
</car>

###

# Удалить объект
DELETE http://localhost:8080/api/v1/car/delete?id=03ea570d-bd63-4ee1-bd63-df9032c32104
content-type: application/xml

###

# Зарезервировать автомобиль
PUT http://localhost:8080/api/v1/car/reserve?id=03ea570d-bd63-4ee1-bd63-df9032c32104
content-type: application/xml

###

# Отменить резервирование автомобиля
PUT http://localhost:8080/api/v1/car/cancel_reserve?id=03ea570d-bd63-4ee1-bd63-df9032c32104
content-type: application/xml

###

# Получить статус резерва по id автомобиля
GET http://localhost:8080/api/v1/car/is_reserved?id=03ea570d-bd63-4ee1-bd63-df9032c32104
content-type: application/xml
