== Требования к проекту

=== Общие требования к запросам / ответам
- Связывайте данные посредством JAXB

=== Требования к реализации дополнительных сервисов
* Логгер
** Все ошибки при работе с API должны логироваться
** Реализуйте несколько уровней логирования
*** ALL- все события
*** ERROR- ошибки времени выполнения
*** FATAL- ошибки, ведущие к завершению работы приложения
** Поддержите вывод
*** В консоль
*** В текстовый файл
**  Поддержите формат события
*** Дата и время события в формате ISO-8601 (паттерн yyyy-MM-dd'T'HH:mm:ss.SSSZ), уровень логирования, текст сообщения
** Реализуйте настройку логгера (уровень логирования, таргетирование) через property файл приложения
* Аудит
** Любое изменение сущности (создание, обновление состояния, удаление) должно сопровождаться вызовом сервиса Аудита
** Сервис Аудита считывает метаинформацию из аннотации и принимает решение, какой тип сущности необходимо обработать. Далее формируется событие аудита.
** Формат события представлен в файле *PersonAuditEvent.xml* пакета com.kdk.sberuniversity.audit.sample
** Событие должно сохраняться в текстовый файл с именем *AuditEvents_ENTITYNAME_yyyy-MM-dd.log*
* Маппинг- сервис
** Реализовать двунаправленный маппинг: DAO в MODEL и обратно

=== Прочие требования
* Реализуйте аннотацию
** Тип- маркерная аннотация для методов, которые изменяют состояние сущностей в сервисном слое
** При обращении к сервису Аудита проверяйте наличие аннотации в вызывающем методе
* Используйте generic и widlcards в классах везде, где это оправдано
* Новые классы должны быть размещены в соответствующих пакетах
* Выделите и используйте свои исключения, унаследовав их от родительского Exception
* Внедрение зависимостей осуществляйте через DIContainer (см. пакет com.kdk.sberuniversity.core.di)
* Сопроводите свое решение примером запросов к REST API, как это представлено в README.MD
* Необходимо реализовать собственный маппер и логгер, использование готовых библиотек запрещено